// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForInsertDiscordPlayerGuilds implements pgx.CopyFromSource.
type iteratorForInsertDiscordPlayerGuilds struct {
	rows                 []InsertDiscordPlayerGuildsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertDiscordPlayerGuilds) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertDiscordPlayerGuilds) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].GuildID,
		r.rows[0].DiscordPlayerID,
	}, nil
}

func (r iteratorForInsertDiscordPlayerGuilds) Err() error {
	return nil
}

func (q *Queries) InsertDiscordPlayerGuilds(ctx context.Context, arg []InsertDiscordPlayerGuildsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"public", "discord_player_guilds"}, []string{"guild_id", "discord_player_id"}, &iteratorForInsertDiscordPlayerGuilds{rows: arg})
}
