// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DailyRosterPosition string

const (
	DailyRosterPositionPG DailyRosterPosition = "PG"
	DailyRosterPositionSG DailyRosterPosition = "SG"
	DailyRosterPositionSF DailyRosterPosition = "SF"
	DailyRosterPositionPF DailyRosterPosition = "PF"
	DailyRosterPositionC  DailyRosterPosition = "C"
)

func (e *DailyRosterPosition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DailyRosterPosition(s)
	case string:
		*e = DailyRosterPosition(s)
	default:
		return fmt.Errorf("unsupported scan type for DailyRosterPosition: %T", src)
	}
	return nil
}

type NullDailyRosterPosition struct {
	DailyRosterPosition DailyRosterPosition
	Valid               bool // Valid is true if DailyRosterPosition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDailyRosterPosition) Scan(value interface{}) error {
	if value == nil {
		ns.DailyRosterPosition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DailyRosterPosition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDailyRosterPosition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DailyRosterPosition), nil
}

type DailyRoster struct {
	GuildID         string
	DiscordPlayerID string
	NbaPlayerUid    pgtype.UUID
	Date            pgtype.Date
	Nickname        string
	Position        DailyRosterPosition
}

// Tracks servers the user has ever played it
type DiscordPlayerGuild struct {
	DiscordPlayerID string
	GuildID         string
}

type IsLocked struct {
	Date     pgtype.Date
	LockTime pgtype.Timestamptz
}

type NbaPlayer struct {
	NbaPlayerUid pgtype.UUID
	NbaPlayerID  int32
	Name         string
	Date         string
	AgainstTeam  pgtype.Int4
	DollarValue  pgtype.Int4
	FantasyScore pgtype.Float8
	TeamID       pgtype.Int4
	Position     string
	AvgPts       pgtype.Float4
	AvgReb       pgtype.Float4
	AvgStl       pgtype.Float4
	AvgAst       pgtype.Float4
	AvgTov       pgtype.Float4
	AvgBlk       pgtype.Float4
	JerseyNum    pgtype.Text
	Status       pgtype.Text
	Reb          pgtype.Int4
	Ast          pgtype.Int2
	Pts          pgtype.Int2
	Blk          pgtype.Int2
	Stl          pgtype.Int2
	Tov          pgtype.Int2
}

type Team struct {
	TeamID int32
	Name   string
	Abbr   pgtype.Text
}
