// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
)

const getAllDailyRoster = `-- name: GetAllDailyRoster :many
select guild_id, discord_player_id from public.daily_roster
`

type GetAllDailyRosterRow struct {
	GuildID         string
	DiscordPlayerID string
}

func (q *Queries) GetAllDailyRoster(ctx context.Context) ([]GetAllDailyRosterRow, error) {
	rows, err := q.db.Query(ctx, getAllDailyRoster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDailyRosterRow
	for rows.Next() {
		var i GetAllDailyRosterRow
		if err := rows.Scan(&i.GuildID, &i.DiscordPlayerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscordPlayerGuilds = `-- name: GetDiscordPlayerGuilds :many
select discord_player_id, guild_id from public.discord_player_guilds
`

func (q *Queries) GetDiscordPlayerGuilds(ctx context.Context) ([]DiscordPlayerGuild, error) {
	rows, err := q.db.Query(ctx, getDiscordPlayerGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscordPlayerGuild
	for rows.Next() {
		var i DiscordPlayerGuild
		if err := rows.Scan(&i.DiscordPlayerID, &i.GuildID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctDailyRoster = `-- name: GetDistinctDailyRoster :many
select distinct guild_id, discord_player_id from public.daily_roster
`

type GetDistinctDailyRosterRow struct {
	GuildID         string
	DiscordPlayerID string
}

func (q *Queries) GetDistinctDailyRoster(ctx context.Context) ([]GetDistinctDailyRosterRow, error) {
	rows, err := q.db.Query(ctx, getDistinctDailyRoster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctDailyRosterRow
	for rows.Next() {
		var i GetDistinctDailyRosterRow
		if err := rows.Scan(&i.GuildID, &i.DiscordPlayerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertDiscordPlayerGuildsParams struct {
	GuildID         string
	DiscordPlayerID string
}
